(provide 'tycho-keybindings)

(require 'ace-jump-mode)
(require 'space-chord)
; (require 'key-chord)
; (key-chord-mode 1)

; (global-set-key (kbd "C-h e") 'help)

(global-set-key (kbd "C-.") 'ace-jump-word-mode)
(global-set-key (kbd "C-,") 'ace-jump-line-mode)
(global-set-key (kbd "C-c s w") 'ispell-word)
(global-set-key (kbd "C-h") 'backward-kill-word)
(global-set-key (kbd "C-x C-h") 'help)
(global-set-key (kbd "C-x C-x") 'exchange-dot-and-mark)
(global-set-key (kbd "C-c s c") 'ispell-complete-word)
(global-set-key (kbd "C-<tab>") 'hippie-expand)
(global-set-key (kbd "C-c <tab>") 'yas/insert-snippet)
(global-set-key (kbd "C-c C-<tab>") 'yas/insert-snippet)
(global-set-key (kbd "C-x c") 'compile)

(global-set-key (kbd "C-S-o") 'my-occur)

(global-set-key (kbd "C-c t b") 'tychoishg-eneric-sphinx-compile)
(global-set-key (kbd "C-c t d") 'tychoish-mark-task-done)
(global-set-key (kbd "C-c t t") 'todo)
(global-set-key (kbd "C-c t c") 'todo-compile)
(global-set-key (kbd "C-c t f") 'flow)

(global-set-key (kbd "C-c o") 'occur)
(define-key isearch-mode-map (kbd "C-o") 'isearch-occur)

(global-set-key (kbd "C-c i") 'indent-region)
(global-set-key (kbd "C-c c") 'comment-region)
(global-set-key (kbd "C-c t w") 'tycho-toggle-hooks)

(global-set-key (kbd "C-c C-r") 'rename-buffer)
(global-set-key (kbd "C-c r") 'replace-word-at-point)
(global-set-key (kbd "C-c C-w") 'whitespace-cleanup)

(global-set-key (kbd "C-x C-d") 'ido-dired)
(global-set-key (kbd "C-c C-p") 'set-mark-command)
(global-set-key (kbd "C-x C-b") 'electric-buffer-list)

(global-unset-key (kbd "C-x C-u"))
(global-set-key (kbd "C-w") 'kill-region)
(global-set-key (kbd "C-c C-a w") 'markdown-insert-wiki-link)

(global-unset-key (kbd "C-x C-u"))
(global-set-key (kbd "C-x C-u t") 'upcase-initials-region)
(global-set-key (kbd "C-x C-u r") 'upcase-region)
(global-set-key (kbd "C-x C-u w") 'upcase-word)

(global-set-key (kbd "C-M-J") (lambda () (interactive) (swap-with 'down)))
(global-set-key (kbd "C-M-K") (lambda () (interactive) (swap-with 'up)))
(global-set-key (kbd "C-M-H") (lambda () (interactive) (swap-with 'left)))
(global-set-key (kbd "C-M-L") (lambda () (interactive) (swap-with 'right)))

(global-set-key (kbd "M-J") (lambda () (interactive) (enlarge-window 1)))
(global-set-key (kbd "M-K") (lambda () (interactive) (enlarge-window -1)))
(global-set-key (kbd "M-H") (lambda () (interactive) (enlarge-window -1 t)))
(global-set-key (kbd "M-L") (lambda () (interactive) (enlarge-window 1 t)))

(global-set-key (kbd "M-j") 'windmove-down)
(global-set-key (kbd "M-k") 'windmove-up)
(global-set-key (kbd "M-h") 'windmove-left)
(global-set-key (kbd "M-l") 'windmove-right)

(global-set-key (kbd "C-x C-n") 'word-count)
(global-set-key (kbd "C-x l") 'goto-line)
(global-set-key (kbd "C-x y") 'rotate-yank-pointer)

(global-set-key (kbd "C-c h h") 'hide-region-hide)
(global-set-key (kbd "C-c h u") 'hide-region-unhide)
(global-set-key (kbd "C-x r h") 'hide-region-hide)
(global-set-key (kbd "C-x r u") 'hide-region-unhide)

(global-set-key (kbd "<f9>") 'th-shell-popup)

(defalias 'afm 'auto-fill-mode)
(defalias 'mm 'markdown-mode)
(defalias 'rm 'rst-mode)
(defalias 'rb 'revert-buffer)
(defalias 'revert 'revert-buffer)
(defalias 'qrr 'query-replace-regexp)
(defalias 'qr 'query-replace)
(defalias 'srr 'string-replace-regexp)
(defalias 'sr 'string-replace)
(defalias 'fs 'flyspell-mode)
(defalias 'fsb 'flyspell-buffer)
(defalias 'uf 'unfill-region)
(defalias 'ss 'server-start)
(defalias 'se 'server-edit)
(defalias 'nf 'new-frame)
(defalias 'eb 'eval-buffer)
(defalias 'mbm 'menu-bar-mode)
(defalias 'dr 'delete-region)
(defalias 'hlm 'hl-line-mode)
(defalias 'dw 'delete-trailing-witespace)
