(require 'rainbow-mode)
(require 'color-theme)
(color-theme-initialize)
;; Color theme based on Tango Palette. Created by danranx@gmail.com

(defun color-theme-undo ()
  (interactive)
  (color-theme-reset-faces)
  (color-theme-snapshot))
(fset 'color-theme-snapshot (color-theme-make-snapshot))
(setq color-theme-is-cumulative nil)

(defun theme-auto-dark-test ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/754409/"
  (interactive)
  (color-theme-install
   '(sweyla754409
     ((background-color . "#010800")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232" :box (:line-width -1 :style released-button)))))
     (mode-line-inactive ((t (:foreground "#323232" :background "#ffffff" :box (:line-width -1 :style released-button)))))
     (modeline-buffer-id ((t (:bold t nil))))
     (modeline-mousable ((t (:background "black" :foreground "light gray" :box (:line-width -1 :style released-button)))))
     (modeline-mousable-minor-mode ((t (:background "black" :foreground "white" :box (:line-width -1 :style released-button)))))

     (region ((t (:background "#323232"))))


     (font-lock-comment-face ((t (:foreground "#FF815F"))))
     (font-lock-constant-face ((t (:foreground "#E7FFBF"))))
     (font-lock-builtin-face ((t (:foreground "#AA63A8"))))
     (font-lock-function-name-face ((t (:foreground "#7005FF"))))
     (font-lock-variable-name-face ((t (:foreground "#6652AE"))))
     (font-lock-keyword-face ((t (:foreground "#B7A5FF"))))
     (font-lock-string-face ((t (:foreground "#BD4EFF"))))
     (font-lock-doc-string-face ((t (:foreground "#BD4EFF"))))
     (font-lock-type-face ((t (:foreground "#FF00D0"))))
     (font-lock-rst-level-face-base-color ((t (:background "#010800" :foreground "#AA63A8"))))
     )))


(defun color-theme-cobalt ()
  "Color theme by Nick Ewing, based off the TextMate Cobalt theme, created 2010-04-16"
  (interactive)
  (color-theme-install
   '(color-theme-cobalt
     ((background-color . "#002240")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#A7A7A7")
      (foreground-color . "#F8F8F8"))
     (default ((t (:background "#09223F" :foreground "white"))))
     (buffers-tab ((t (:background "#09223F" :foreground "white"))))
     (font-lock-doc-face ((t (:foreground "#008AFF"))))
     (font-lock-function-name-face ((t (:foreground "#FFDD00"))))
     (font-lock-keyword-face ((t (:foreground "#FA9E18"))))
     (font-lock-preprocessor-face ((t (:foreground "#8090A2"))))
     (font-lock-reference-face ((t (:foreground "#CCCCCC"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))
     (font-lock-string-face ((t (:foreground "#42D915"))))
     (font-lock-type-face ((t (:foreground "#FFEF79"))))
     (font-lock-variable-name-face ((t (:foreground "#CCCCCC"))))
     (font-lock-warning-face ((t (:foreground "Pink"))))
     (hl-line ((t (:background "#00162A"))))
     (linum ((t (:background "#111111" :foreground "#888888"
                 :underline nil))))
     (gui-element ((t (:background "#303030" :foreground "black"))))
     (region ((t (:background "#444444"))))
     (highlight ((t (:background "#26425D"))))
     (show-paren-match ((t (:background "#26425D"))))
     (show-paren-mismatch ((t (:background "#FF0000"))))
     (ecb-default-highlight-face ((t (:background "#26425D"))))
     (minibuffer-prompt ((t (:foreground "#008AFF"))))
     (modeline ((t (:background "#222222" :foreground "#dcdcdc" :box (:line-width -1 :style released-button)))))
     (modeline-inactive ((t (:background "#121212" :foreground "#ababab":box (:line-width -1 :style released-button)))))
     (modeline-highlight ((((class color) (min-colors 88)) nil)))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (toolbar ((t (nil))))
     (ido-subdir ((t (:foreground "#008AFF"))))
     (ido-only-match ((t (:foreground "#42D915"))))
     (mumamo-background-chunk-major ((t (:background nil))))
     (mumamo-background-chunk-submode1 ((t (:background nil))))
     (underline ((nil (:underline nil)))))))
(setq rst-level-face-base-color nil)

(defun color-theme-tycho-awesome ()
  "Color theme by Gordon Messmer, created 2001-02-07.
A color theme inspired by a certain IDE for Windows.  It's all from memory,
since I only used that software in college.

If you want to modify the font as well, you should customize variable
`color-theme-legal-frame-parameters' to \"\\(color\\|mode\\|font\\|height\\|width\\)$\".
The default setting will prevent color themes from installing specific
fonts."
  (interactive)
  (color-theme-install
   '(color-theme-midnight
     ((font . "fixed")
      (width . 130)
      (height . 50)
      (background-color . "#2e3440")
      (foreground-color . "grey80")
      (background-mode . dark)
      (mouse-color . "grey85")
      (cursor-color . "grey85"))
     (default ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
    ; (font-lock-builtin-face ((t (:foreground "#40FFB9"))))
     (font-lock-comment-face ((t (:foreground "#008AFF"))))
     (font-lock-constant-face ((t (:foreground "#aa518E"))))
     ;; (font-lock-builtin-face ((t (:foreground "SkyBlue"))))
     ;; (font-lock-comment-face ((t (:italic t :foreground "grey60"))))
     ;; (font-lock-constant-face ((t (:foreground "OliveDrab"))))
     (font-lock-string-face ((t (:foreground "#42D915"))))
     (font-lock-keyword-face ((t (:foreground "Cyan"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink"))))
     (font-lock-type-face ((t (:foreground "Cyan"))))
     (font-lock-variable-name-face ((t (:foreground "DarkGoldenrod"))))
     (font-lock-function-name-face ((t (:foreground "SlateBlue"))))
     (highline-face ((t (:background "grey12"))))
     (setnu-line-number-face ((t (:background "Grey15" :foreground "White" :bold t))))
     (show-paren-match-face ((t (:background "grey30"))))
     (region ((t (:background "grey15"))))
     (highlight ((t (:background "blue"))))
     (secondary-selection ((t (:background "navy"))))
     (widget-field-face ((t (:background "navy"))))
     (widget-single-line-field-face ((t (:background "#002240")))))) )

(defun color-theme-less ()
  "A minimalistic color scheme by Jason Blevins, created 2008-10-07.
Inspired by color-theme-late-night and the Less is More theme for vim."
  (interactive)
  (let ((color-theme-is-cumulative t))
;    (color-theme-dark-erc)
;    (color-theme-dark-gnus)
;    (color-theme-dark-info)
    (color-theme-install
     '(color-theme-less
       ((background-color . "#000")
        (background-mode . dark)
        (background-toolbar-color . "#000")
        (border-color . "#000")
        (bottom-toolbar-shadow-color . "#000")
        (cursor-color	. "yellow")
        (foreground-color . "gray70")
        (top-toolbar-shadow-color . "#111"))

       ;; Standard font lock faces
       (default ((t (nil))))
       (bold ((t (:bold t))))
       (italic ((t (:bold t))))
       (underline ((t (:bold t))))
       (variable-pitch ((t (nil))))
       (font-lock-comment-face ((t (:bold t :foreground "dim gray"))))
       (font-lock-comment-delimiter-face ((t (:bold t :foreground "dim gray"))))
       (font-lock-function-name-face ((t (:foreground "gray90"))))
       (font-lock-variable-name-face ((t (:foreground "gray90"))))
       (font-lock-constant-face ((t (:foreground "gray90"))))
       (font-lock-doc-string-face ((t (:foreground "gray90"))))
       (font-lock-doc-face ((t (:foreground "gray90"))))
       (font-lock-preprocessor-face ((t (:foreground "gray90"))))
       (font-lock-reference-face ((t (:foreground "gray90"))))
       (font-lock-string-face ((t (:foreground "gray90"))))
       (font-lock-type-face ((t (:bold t :foreground "white"))))
       (font-lock-builtin-face ((t (:bold t :foreground "white"))))
       (font-lock-keyword-face ((t (:bold t :foreground "white"))))
       (font-lock-warning-face ((t (:bold t :foreground "red"))))


     (modeline ((t (:background "#222222" :foreground "#dcdcdc" ))))
     (modeline-inactive ((t (:background "#121212" :foreground "#ababab"))))
     (modeline-highlight ((((class color) (min-colors 88)) nil)))
     (modeline-buffer-id ((t (:bold t nil))))



       ;; Emacs Interface
       (fringe ((t (:background "#111" :foreground "#444"))))
       (header-line ((t (:background "#333" :foreground "#000"))))
       (menu ((t (:background "#111" :foreground "#444"))))
       (minibuffer-prompt ((t (:foreground "white"))))
       (modeline ((t (:background "gray20" :foreground "white" :box (:line-width -1 :style released-button)))))
       (mode-line-inactive ((t (:background "gray20" :foreground "light gray" :box (:line-width -1 :style released-button)))))
       (modeline-buffer-id ((t (:background "gray20" :foreground "light gray" :box (:line-width -1 :style released-button)))))
       (modeline-mousable ((t (:background "black" :foreground "light gray" :box (:line-width -1 :style released-button)))))
       (modeline-mousable-minor-mode ((t (:background "black" :foreground "white" :box (:line-width -1 :style released-button)))))
       (region ((t (:background "light gray" :foreground "black"))))
       (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
       (tool-bar ((t (:background "#111" :foreground "#777"))))
       (tooltip ((t (:background "#333" :foreground "#777"))))
       (widget-button-face ((t (:bold t :foreground "#888"))))
       (widget-field-face ((t (:bold t :foreground "#999"))))

       ;; Search
       (isearch ((t (:foreground "black" :background "red"))))
       (isearch-lazy-highlight-face ((t (:foreground "red"))))

       ;; Parenthesis matching
       (show-paren-match-face ((t (:foreground "black" :background "light gray"))))
       (show-paren-mismatch-face ((t (:foreground "black" :background "red"))))

       ;; Line highlighting
       (highlight ((t (:background "#1f1f1f" :foreground nil))))
       (highlight-current-line-face ((t (:background "#1f1f1f" :foreground nil))))
       (hl-line ((t (:background "#1f1f1f" :foreground nil))))

       ;; Buttons
       (button ((t (:bold t))))
       (custom-button-face ((t (:bold t :foreground "#999"))))

       ;; Calendar
       (holiday-face ((t (:background "#000" :foreground "#777"))))
       ))))

(defun color-theme-subdued ()
  "Subdued color theme for Emacs by Jason Blevins.
Based on the Tango color palette."
  (interactive)
  (color-theme-install
   '(color-theme-subdued
     ((foreground-color . "#d3d7cf")
      (background-color . "#000")
;      (background-color . "#002240")
      (background-mode . dark)
      (cursor-color . "#73d216") ; medium chameleon
      (mouse-color . "#73d216"))

     ;;; Standard font lock faces
     (default ((t (nil))))
     (font-lock-comment-face ((t (:foreground "#61635e")))) ; dark aluminum
     (font-lock-comment-delimiter-face ((t (:foreground "#61635e")))) ; dark aluminum
     (font-lock-doc-face ((t (:foreground "#77507b")))) ; plum
     (font-lock-doc-string-face ((t (:foreground "#77507b")))) ; plum
     (font-lock-string-face ((t (:foreground "#77507b")))) ; plum
     (font-lock-keyword-face ((t (:foreground "#729fcf")))) ; light sky blue
     (font-lock-builtin-face ((t (:foreground "#855c1b")))) ; med-dark chocolate
     (font-lock-function-name-face ((t (:foreground "#c4a000")))) ; dark butter
     (font-lock-variable-name-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "#888a85")))) ; aluminum
     (font-lock-constant-face ((t (:foreground "#4e9a06")))) ; dark chameleon
     (font-lock-type-face ((t (:foreground "#ad7fa8")))) ; light plum
     (font-lock-warning-face ((t (:bold t :foreground "#cc0000")))) ; scarlet red

     ;; Search
     (isearch ((t (:foreground "#080808" :background "#edd400"))))
     (isearch-lazy-highlight-face ((t (:foreground "#080808" :background "#2e3436"))))

     ;; Emacs Interface
     (fringe ((t (:background "#0f0f0f"))))
     (border ((t (:background "#0f0f0f"))))
     (mode-line ((t (:background "#1f1f1f" :foreground "#eeeeec" :box (:line-width -1 :style released-button)))))
;     (mode-line-buffer-id ((t (:background "#1f1f1f" :foreground "#eeeeec" :box (:line-width -1 :style released-button)))))
     (mode-line-inactive ((t (:background "#1f1f1f" :foreground "#888a85" :box (:line-width -1 :style released-button)))))
     (minibuffer-prompt ((t (:foreground "#729fcf")))) ; light sky blue
     (region ((t (:background "#2e3436"))))

     ;; Parenthesis matching
     (show-paren-match-face ((t (:foreground "#2e3436" :background "#73d216"))))
     (show-paren-mismatch-face ((t (:foreground "#2e3436" :background "#ef2929"))))

     ;; Line highlighting
     (highlight ((t (:background "#1f1f1f" :foreground nil))))
     (highlight-current-line-face ((t (:background "#1f1f1f" :foreground nil))))

     ;; Calendar
     (holiday-face ((t (:foreground "#cc0000")))) ; dark scarlet red

     ;; Info
     (info-xref ((t (:foreground "#729fcf")))) ; light sky blue
     (info-xref-visited ((t (:foreground "#ad7fa8")))) ; light plum

     ;;; AUCTeX
     (font-latex-sectioning-5-face ((t (:foreground "#c4a000" :bold t)))) ; dark butter
     (font-latex-bold-face ((t (:foreground "#4e9a06" :bold t)))) ; dark chameleon
     (font-latex-italic-face ((t (:foreground "#4e9a06" :italic t)))) ; dark chameleon
     (font-latex-math-face ((t (:foreground "#855c1b")))) ; med-dark chocolate
     (font-latex-string-face ((t (:foreground "#77507b")))) ; plum
     (font-latex-warning-face ((t (:foreground "#cc0000")))) ; dark scarlet red
     (font-latex-slide-title-face ((t (:foreground "#c4a000")))) ; dark butter

     ;;; post-mode
     (post-emoticon-face ((t (:background "#edd400" :foreground "#000000")))) ; medium butter
     (post-header-value-face ((t (:foreground "#4e9a06")))) ; dark chameleon
     (post-header-keyword-face ((t (:foreground "#4e9a06" :bold t)))) ; dark chameleon
     (post-signature-text-face ((t (:foreground "#cc0000")))) ; dark scarlet red
     (post-quoted-text-face ((t (:foreground "#855c1b" :slant normal)))) ; med-dark chocolate
     (post-double-quoted-text-face ((t (:foreground "#77507b" :slant normal)))) ; plum
     (post-multiply-quoted-text-face ((t (:foreground "#61635e" :slant normal)))) ; dark aluminum
     (post-email-address-text-face ((t (:foreground "#729fcf" :bold t)))) ; light sky blue
     (post-url-face ((t (:foreground "#729fcf" :bold t)))) ; light sky blue
     )))


(rainbow-mode 1)
;(color-theme-tycho-awesome)
